services:
  bot:
    image: ghcr.io/taurmorchant/happybirthdaybot:latest
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TZ=Europe/Samara
    volumes:
      - ./configs:/config:ro
